### ISSUE TITLE
CRITICAL: 'NoneType' object has no attribute 'exec_module'

### ISSUE THREAD

**Issue by bittner** [kura/pelican_youtube#8]
With [Pelican 4.5.0](https://docs.getpelican.com/en/stable/changelog.html) I get an attribute access error with this plugin. This does not happen with older Pelican versions.

```console
$ pelican
CRITICAL: 'NoneType' object has no attribute 'exec_module'
```

This might be related to #6.

I also noticed that the [getpelican/pelican-plugins](https://github.com/getpelican/pelican-plugins) repository doesn't reference the latest commit of this repository. Though, manually updating the Git submodule reference doesn't seem to help with this specific problem.

Any ideas how we can fix this issue here?

**Comment by lokke3** [comment]
I also get this with Pelican 4.5.1

**Comment by kura** [comment]
I will take a look.

**Comment by kura** [comment]
So this appears to be an issue with how this code base is set up to allow it to be pip installable.

If you want to have it in a plugins directory you can do the following:

- `git clone` it to your `plugins` directory
- `mv $your_plugins_dir/pelican_youtube/pelican_youtube/* $your_plugins_dir/pelican_youtube`

**Comment by kura** [comment]
This has now been fixed with symlinks.

**Comment by bittner** [comment]
Related update on the Pelican project: https://github.com/getpelican/pelican-plugins/pull/1410
